apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: srv-geo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: "60s"
        autoscaling.knative.dev/stable-window: "60s"  # Default: 60s, Duration, 6s <= value <= 1h
        autoscaling.knative.dev/panic-window-percentage: "10.0" # Possible values: float, 1.0 <= value <= 100.0
        autoscaling.knative.dev/panic-threshold-percentage: "200.0" # Default: 200.0, Possible values: float, 110.0 <= value <= 1000.0
        autoscaling.knative.dev/initial-scale: "1"
        autoscaling.knative.dev/min-scale: "0" # 0 = no min
        autoscaling.knative.dev/max-scale: "0" # 0 = no max
        autoscaling.knative.dev/scale-down-delay: "0s" # Duration, 0s <= value <= 1h
        autoscaling.knative.dev/activation-scale: "5"
        autoscaling.knative.dev/metric: "concurrency" # "concurrency", "rps", "cpu"*, "memory"*. *requires hpa.autoscaling
        autoscaling.knative.dev/target: "100"
        autoscaling.knative.dev/target-utilization-percentage: "70" # hotness of the target value to scale on.
    spec:
      containers:
      - command:
        - geo
        env:
        - name: DLOG
          value: DEBUG
        image: pag3r/hotel-reservations:latest
        name: hotel-reserv-geo
        ports:
          - name: h2c
            containerPort: 8083
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 1000m
