apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: srv-user
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: "6s"
        autoscaling.knative.dev/stable-window: "6s"  # Default: 60s, Duration, 6s <= value <= 1h
        autoscaling.knative.dev/panic-window-percentage: "1.0" # Possible values: float, 1.0 <= value <= 100.0
        autoscaling.knative.dev/panic-threshold-percentage: "500.0" # Default: 200.0, Possible values: float, 110.0 <= value <= 1000.0
        autoscaling.knative.dev/initial-scale: "1"
        autoscaling.knative.dev/min-scale: "0" # 0 = no min
        autoscaling.knative.dev/max-scale: "3" # 0 = no max
        autoscaling.knative.dev/scale-down-delay: "0s" # Duration, 0s <= value <= 1h
        autoscaling.knative.dev/activation-scale: "3"
        autoscaling.knative.dev/metric: "concurrency" # "concurrency", "rps", "cpu"*, "memory"*. *requires hpa.autoscaling
        autoscaling.knative.dev/target: "10"
        # autoscaling.knative.dev/target-utilization-percentage: "100" # hotness of the target value to scale on.
    spec:
      containers:
      - command:
        - user
        env:
        - name: DLOG
          value: DEBUG
        image: pag3r/hotel-reservations:latest
        name: hotel-reserv-user
        ports:
          - name: h2c
            containerPort: 8086
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 500m
